name: Performance Monitoring and Analytics

on:
  schedule:
    # Run every 6 hours for performance monitoring
    - cron: '0 */6 * * *'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'package.json'
      - 'requirements.txt'
      - 'go.mod'
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'package.json'
      - 'requirements.txt'
      - 'go.mod'

env:
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.11'
  GO_VERSION: '1.21'

jobs:
  performance-monitoring:
    name: Performance Monitoring
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Node.js for front-end performance testing
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Install Playwright
      run: npx playwright install --with-deps
      
    - name: Run synthetic performance tests
      run: |
        npx playwright test --config=playwright.config.ts --reporter=html
      env:
        PLAYWRIGHT_BROWSERS_PATH: 0
        
    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-performance-report
        path: playwright-report/
        retention-days: 30

  load-testing:
    name: API Load Testing
    runs-on: ubuntu-latest
    timeout-minutes: 45
    if: github.event_name == 'schedule' || contains(github.event.head_commit.message, '[load-test]')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Start application
      run: |
        npm run start &
        sleep 10
        
    - name: Install k6
      run: |
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
        echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        sudo apt-get install k6
        
    - name: Run load tests
      run: |
        k6 run --out json=load-test-results.json k6/load-test.js
        
    - name: Analyze load test results
      run: |
        node scripts/analyze-load-test.js load-test-results.json
        
    - name: Upload load test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: load-test-results
        path: |
          load-test-results.json
          load-test-analysis.json
        retention-days: 7

  memory-profiling:
    name: Memory and CPU Profiling
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: github.event_name == 'schedule'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Install clinic.js
      run: npm install -g @clinic/clinic
      
    - name: Run memory profiling
      run: |
        clinic doctor --on-port 'node scripts/memory-test.js' -- node memory-profile.js
        
    - name: Upload profiling results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: profiling-results
        path: |
          .clinic/
          profiling-summary.txt
        retention-days: 7

  repository-health-analytics:
    name: Repository Health Analytics
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install repository analytics tools
      run: |
        npm install -g @octokit/rest
        npm install @actions/github
        
    - name: Collect repository statistics
      run: |
        node scripts/repository-stats.js > repository-stats.json
        
    - name: Analyze contributor trends
      run: |
        node scripts/contributor-analysis.js > contributor-analysis.json
        
    - name: Generate health report
      run: |
        node scripts/generate-health-report.js
        
    - name: Upload health analytics
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: repository-health-analytics
        path: |
          repository-stats.json
          contributor-analysis.json
          health-report.md
        retention-days: 30

  community-engagement-metrics:
    name: Community Engagement Metrics
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Analyze community engagement
      run: |
        node scripts/community-metrics.js > community-metrics.json
        
    - name: Track issue resolution time
      run: |
        node scripts/issue-resolution-analysis.js > issue-resolution.json
        
    - name: Monitor PR review velocity
      run: |
        node scripts/pr-velocity-analysis.js > pr-velocity.json
        
    - name: Upload community metrics
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: community-engagement-metrics
        path: |
          community-metrics.json
          issue-resolution.json
          pr-velocity.json
        retention-days: 30

  slack-notification:
    name: Send Performance Summary
    runs-on: ubuntu-latest
    if: always() && github.event_name == 'schedule'
    needs: [performance-monitoring, load-testing, memory-profiling, repository-health-analytics, community-engagement-metrics]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Generate performance summary
      run: |
        node scripts/performance-summary.js > performance-summary.md
        
    - name: Send to Slack
      uses: 8398a7/action-slack@v3
      if: always()
      with:
        status: ${{ job.status }}
        channel: '#devops'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        fields: repo,message,commit,author,action,eventName,ref,workflow
        custom_payload: |
          {
            text: "Performance Monitoring Results",
            attachments: [{
              color: "${{ job.status == 'success' && 'good' || 'danger' }}",
              fields: [
                {
                  title: "Repository",
                  value: "${{ github.repository }}",
                  short: true
                },
                {
                  title: "Workflow Status",
                  value: "${{ job.status }}",
                  short: true
                },
                {
                  title: "Performance Summary",
                  value: "See attached report",
                  short: false
                }
              ]
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        
    - name: Upload performance summary
      uses: actions/upload-artifact@v4
      with:
        name: performance-summary
        path: performance-summary.md
        retention-days: 30